CREATE TABLE wt_post_time (
  ACTIVITYID INT AUTO_INCREMENT NOT NULL,
  CASEID INT NULL,
  USERNAME CHAR(50) NOT NULL,
  EMAIL CHAR(50) NULL,
  ACTIVITY_CODE NUMERIC(11, 0) NULL,
  NARRATIVE CHAR(254) NULL,
  NARRATIVE_INTERNAL_NOTE CHAR(254) NULL,
  START_TIME DATETIME(3) NOT NULL,
  TOTAL_TIME_SECS BIGINT NULL,
  CHARGEABLE_TIME_SECS BIGINT NULL,
  PRIMARY KEY (ACTIVITYID)
);

create table cases (
  CASE_ID INT NOT NULL,
  IRN CHAR(30),
  CASE_TYPE CHAR(1) NOT NULL,
  TITLE CHAR(254),
  PROPERTY_TYPE CHAR(1) NOT NULL,
  COUNTRY_CODE CHAR(3) NOT NULL
);

create table user_identity (
  IDENTITY_ID INT AUTO_INCREMENT,
  USER_ID INT NOT NULL,
  USERNAME CHAR(50) NOT NULL,
  EMAIL CHAR(254),
  PRIMARY KEY (IDENTITY_ID)
);

create table activity_codes (
  ACTIVITY_CODE NUMERIC(11, 0),
  ACTIVITY_NAME CHAR(50)
);
