CREATE SEQUENCE wt_post_time_seq;

CREATE TABLE wt_post_time (
  ACTIVITYID INT DEFAULT NEXTVAL ('wt_post_time_seq') NOT NULL,
  CASEID INT NULL,
  USERNAME TEXT NOT NULL,
  EMAIL TEXT NULL,
  ACTIVITY_CODE NUMERIC(11, 0) NULL,
  NARRATIVE TEXT NULL,
  NARRATIVE_INTERNAL_NOTE TEXT NULL,
  START_TIME TIMESTAMP(3) NOT NULL,
  TOTAL_TIME_SECS BIGINT NULL,
  CHARGEABLE_TIME_SECS BIGINT NULL,
  PRIMARY KEY (ACTIVITYID)
);

CREATE TABLE CASES (
  CASEID INT NOT NULL,
  IRN CHAR(30),
  CASETYPE CHAR(1) NOT NULL,
  TITLE CHAR(254),
  PROPERTYTYPE CHAR(1) NOT NULL,
  COUNTRYCODE CHAR(3) NOT NULL
);

CREATE SEQUENCE user_identity_seq;

CREATE TABLE USERIDENTITY (
  IDENTITYID INT DEFAULT NEXTVAL ('user_identity_seq'),
  NAMENO INT NOT NULL,
  LOGINID TEXT NOT NULL,
  PRIMARY KEY (IDENTITYID)
);

CREATE TABLE TACTIVITYCODES (
  ACTIVITYCODE NUMERIC(11, 0),
  ACTIVITYNAME CHAR(50),
  ACTIVITYTYPE INT,
  ACTIVITYLA INT
);
