CREATE SEQUENCE wt_post_time_seq;

CREATE TABLE wt_post_time (
  ACTIVITYID INT DEFAULT NEXTVAL ('wt_post_time_seq') NOT NULL,
  CASEID INT NULL,
  USERNAME TEXT NOT NULL,
  EMAIL TEXT NULL,
  ACTIVITY_CODE NUMERIC(11, 0) NULL,
  NARRATIVE TEXT NULL,
  NARRATIVE_INTERNAL_NOTE TEXT NULL,
  START_TIME TIMESTAMP(3) NOT NULL,
  TOTAL_TIME_SECS BIGINT NULL,
  CHARGEABLE_TIME_SECS BIGINT NULL,
  PRIMARY KEY (ACTIVITYID)
);

CREATE TABLE cases (
  CASE_ID INT NOT NULL,
  IRN CHAR(30),
  CASE_TYPE CHAR(1) NOT NULL,
  TITLE CHAR(254),
  PROPERTY_TYPE CHAR(1) NOT NULL,
  COUNTRY_CODE CHAR(3) NOT NULL
);

CREATE SEQUENCE user_identity_seq;

CREATE TABLE user_identity (
  IDENTITY_ID INT DEFAULT NEXTVAL ('user_identity_seq'),
  USER_ID INT NOT NULL,
  USERNAME TEXT NOT NULL,
  EMAIL TEXT,
  PRIMARY KEY (IDENTITY_ID)
);

CREATE TABLE activity_codes (
  ACTIVITY_CODE NUMERIC(11, 0),
  ACTIVITY_NAME CHAR(50)
);
