name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "15 21 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          reviewers: sukolenvo
